/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhoRouteImport } from './routes/trabalho'
import { Route as SympliceRouteImport } from './routes/symplice'
import { Route as SolidRouteImport } from './routes/solid'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as NatraveRouteImport } from './routes/natrave'
import { Route as MaxiRouteImport } from './routes/maxi'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosSistemaDeConteudoRouteImport } from './routes/servicos.sistema-de-conteudo'
import { Route as ServicosPresencaDigitalRouteImport } from './routes/servicos.presenca-digital'
import { Route as ServicosMidiaOohRouteImport } from './routes/servicos.midia-ooh'
import { Route as ServicosMidiaImpressaRouteImport } from './routes/servicos.midia-impressa'
import { Route as ServicosMarketingDeInfluenciaRouteImport } from './routes/servicos.marketing-de-influencia'
import { Route as ServicosEstruturacaoDeMarcaRouteImport } from './routes/servicos.estruturacao-de-marca'
import { Route as BrandBrandIdRouteImport } from './routes/brand.$brandId'

const TrabalhoRoute = TrabalhoRouteImport.update({
  id: '/trabalho',
  path: '/trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const SympliceRoute = SympliceRouteImport.update({
  id: '/symplice',
  path: '/symplice',
  getParentRoute: () => rootRouteImport,
} as any)
const SolidRoute = SolidRouteImport.update({
  id: '/solid',
  path: '/solid',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const NatraveRoute = NatraveRouteImport.update({
  id: '/natrave',
  path: '/natrave',
  getParentRoute: () => rootRouteImport,
} as any)
const MaxiRoute = MaxiRouteImport.update({
  id: '/maxi',
  path: '/maxi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosSistemaDeConteudoRoute =
  ServicosSistemaDeConteudoRouteImport.update({
    id: '/sistema-de-conteudo',
    path: '/sistema-de-conteudo',
    getParentRoute: () => ServicosRoute,
  } as any)
const ServicosPresencaDigitalRoute = ServicosPresencaDigitalRouteImport.update({
  id: '/presenca-digital',
  path: '/presenca-digital',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosMidiaOohRoute = ServicosMidiaOohRouteImport.update({
  id: '/midia-ooh',
  path: '/midia-ooh',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosMidiaImpressaRoute = ServicosMidiaImpressaRouteImport.update({
  id: '/midia-impressa',
  path: '/midia-impressa',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosMarketingDeInfluenciaRoute =
  ServicosMarketingDeInfluenciaRouteImport.update({
    id: '/marketing-de-influencia',
    path: '/marketing-de-influencia',
    getParentRoute: () => ServicosRoute,
  } as any)
const ServicosEstruturacaoDeMarcaRoute =
  ServicosEstruturacaoDeMarcaRouteImport.update({
    id: '/estruturacao-de-marca',
    path: '/estruturacao-de-marca',
    getParentRoute: () => ServicosRoute,
  } as any)
const BrandBrandIdRoute = BrandBrandIdRouteImport.update({
  id: '/brand/$brandId',
  path: '/brand/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/maxi': typeof MaxiRoute
  '/natrave': typeof NatraveRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/solid': typeof SolidRoute
  '/symplice': typeof SympliceRoute
  '/trabalho': typeof TrabalhoRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/servicos/estruturacao-de-marca': typeof ServicosEstruturacaoDeMarcaRoute
  '/servicos/marketing-de-influencia': typeof ServicosMarketingDeInfluenciaRoute
  '/servicos/midia-impressa': typeof ServicosMidiaImpressaRoute
  '/servicos/midia-ooh': typeof ServicosMidiaOohRoute
  '/servicos/presenca-digital': typeof ServicosPresencaDigitalRoute
  '/servicos/sistema-de-conteudo': typeof ServicosSistemaDeConteudoRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/maxi': typeof MaxiRoute
  '/natrave': typeof NatraveRoute
  '/sobre': typeof SobreRoute
  '/solid': typeof SolidRoute
  '/symplice': typeof SympliceRoute
  '/trabalho': typeof TrabalhoRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/servicos/estruturacao-de-marca': typeof ServicosEstruturacaoDeMarcaRoute
  '/servicos/marketing-de-influencia': typeof ServicosMarketingDeInfluenciaRoute
  '/servicos/midia-impressa': typeof ServicosMidiaImpressaRoute
  '/servicos/midia-ooh': typeof ServicosMidiaOohRoute
  '/servicos/presenca-digital': typeof ServicosPresencaDigitalRoute
  '/servicos/sistema-de-conteudo': typeof ServicosSistemaDeConteudoRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/maxi': typeof MaxiRoute
  '/natrave': typeof NatraveRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/solid': typeof SolidRoute
  '/symplice': typeof SympliceRoute
  '/trabalho': typeof TrabalhoRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/servicos/estruturacao-de-marca': typeof ServicosEstruturacaoDeMarcaRoute
  '/servicos/marketing-de-influencia': typeof ServicosMarketingDeInfluenciaRoute
  '/servicos/midia-impressa': typeof ServicosMidiaImpressaRoute
  '/servicos/midia-ooh': typeof ServicosMidiaOohRoute
  '/servicos/presenca-digital': typeof ServicosPresencaDigitalRoute
  '/servicos/sistema-de-conteudo': typeof ServicosSistemaDeConteudoRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/maxi'
    | '/natrave'
    | '/servicos'
    | '/sobre'
    | '/solid'
    | '/symplice'
    | '/trabalho'
    | '/brand/$brandId'
    | '/servicos/estruturacao-de-marca'
    | '/servicos/marketing-de-influencia'
    | '/servicos/midia-impressa'
    | '/servicos/midia-ooh'
    | '/servicos/presenca-digital'
    | '/servicos/sistema-de-conteudo'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/maxi'
    | '/natrave'
    | '/sobre'
    | '/solid'
    | '/symplice'
    | '/trabalho'
    | '/brand/$brandId'
    | '/servicos/estruturacao-de-marca'
    | '/servicos/marketing-de-influencia'
    | '/servicos/midia-impressa'
    | '/servicos/midia-ooh'
    | '/servicos/presenca-digital'
    | '/servicos/sistema-de-conteudo'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/maxi'
    | '/natrave'
    | '/servicos'
    | '/sobre'
    | '/solid'
    | '/symplice'
    | '/trabalho'
    | '/brand/$brandId'
    | '/servicos/estruturacao-de-marca'
    | '/servicos/marketing-de-influencia'
    | '/servicos/midia-impressa'
    | '/servicos/midia-ooh'
    | '/servicos/presenca-digital'
    | '/servicos/sistema-de-conteudo'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  MaxiRoute: typeof MaxiRoute
  NatraveRoute: typeof NatraveRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SobreRoute: typeof SobreRoute
  SolidRoute: typeof SolidRoute
  SympliceRoute: typeof SympliceRoute
  TrabalhoRoute: typeof TrabalhoRoute
  BrandBrandIdRoute: typeof BrandBrandIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalho': {
      id: '/trabalho'
      path: '/trabalho'
      fullPath: '/trabalho'
      preLoaderRoute: typeof TrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symplice': {
      id: '/symplice'
      path: '/symplice'
      fullPath: '/symplice'
      preLoaderRoute: typeof SympliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solid': {
      id: '/solid'
      path: '/solid'
      fullPath: '/solid'
      preLoaderRoute: typeof SolidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natrave': {
      id: '/natrave'
      path: '/natrave'
      fullPath: '/natrave'
      preLoaderRoute: typeof NatraveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maxi': {
      id: '/maxi'
      path: '/maxi'
      fullPath: '/maxi'
      preLoaderRoute: typeof MaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/sistema-de-conteudo': {
      id: '/servicos/sistema-de-conteudo'
      path: '/sistema-de-conteudo'
      fullPath: '/servicos/sistema-de-conteudo'
      preLoaderRoute: typeof ServicosSistemaDeConteudoRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/presenca-digital': {
      id: '/servicos/presenca-digital'
      path: '/presenca-digital'
      fullPath: '/servicos/presenca-digital'
      preLoaderRoute: typeof ServicosPresencaDigitalRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/midia-ooh': {
      id: '/servicos/midia-ooh'
      path: '/midia-ooh'
      fullPath: '/servicos/midia-ooh'
      preLoaderRoute: typeof ServicosMidiaOohRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/midia-impressa': {
      id: '/servicos/midia-impressa'
      path: '/midia-impressa'
      fullPath: '/servicos/midia-impressa'
      preLoaderRoute: typeof ServicosMidiaImpressaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/marketing-de-influencia': {
      id: '/servicos/marketing-de-influencia'
      path: '/marketing-de-influencia'
      fullPath: '/servicos/marketing-de-influencia'
      preLoaderRoute: typeof ServicosMarketingDeInfluenciaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/estruturacao-de-marca': {
      id: '/servicos/estruturacao-de-marca'
      path: '/estruturacao-de-marca'
      fullPath: '/servicos/estruturacao-de-marca'
      preLoaderRoute: typeof ServicosEstruturacaoDeMarcaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/brand/$brandId': {
      id: '/brand/$brandId'
      path: '/brand/$brandId'
      fullPath: '/brand/$brandId'
      preLoaderRoute: typeof BrandBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicosRouteChildren {
  ServicosEstruturacaoDeMarcaRoute: typeof ServicosEstruturacaoDeMarcaRoute
  ServicosMarketingDeInfluenciaRoute: typeof ServicosMarketingDeInfluenciaRoute
  ServicosMidiaImpressaRoute: typeof ServicosMidiaImpressaRoute
  ServicosMidiaOohRoute: typeof ServicosMidiaOohRoute
  ServicosPresencaDigitalRoute: typeof ServicosPresencaDigitalRoute
  ServicosSistemaDeConteudoRoute: typeof ServicosSistemaDeConteudoRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosEstruturacaoDeMarcaRoute: ServicosEstruturacaoDeMarcaRoute,
  ServicosMarketingDeInfluenciaRoute: ServicosMarketingDeInfluenciaRoute,
  ServicosMidiaImpressaRoute: ServicosMidiaImpressaRoute,
  ServicosMidiaOohRoute: ServicosMidiaOohRoute,
  ServicosPresencaDigitalRoute: ServicosPresencaDigitalRoute,
  ServicosSistemaDeConteudoRoute: ServicosSistemaDeConteudoRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  MaxiRoute: MaxiRoute,
  NatraveRoute: NatraveRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SobreRoute: SobreRoute,
  SolidRoute: SolidRoute,
  SympliceRoute: SympliceRoute,
  TrabalhoRoute: TrabalhoRoute,
  BrandBrandIdRoute: BrandBrandIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
